---
- name: Include common tasks
  ansible.builtin.include_role:
    name: kubernetes_common

- name: Fetch the join command from local file
  ansible.builtin.slurp:
    src: join_command.sh
  register: join_command

- name: Decode the join command
  ansible.builtin.set_fact:
    decoded_join_command: "{{ join_command['content'] | b64decode }}"
  when: join_command.changed

- name: Notify handler to join the cluster
  ansible.builtin.meta: flush_handlers
  notify: Join the cluster
  when: join_command.changed
