---
- name: Include common tasks
  ansible.builtin.include_role:
    name: kubernetes_common

- name: Initialize the Kubernetes cluster
  ansible.builtin.command: kubeadm init --pod-network-cidr={{ kubernetes_network_cidr }} --kubernetes-version="{{ kubernetes_version }}"
  args:
    creates: /etc/kubernetes/admin.conf
  register: init_output

- name: Notify handler to save kubeadm join command
  ansible.builtin.meta: flush_handlers
  notify: Save kubeadm join command
  when: init_output is changed
