---
- name: Include common tasks
  ansible.builtin.include_role:
    name: kubernetes_common

- name: Initialize the Kubernetes cluster
  ansible.builtin.command: kubeadm init --pod-network-cidr={{ kubernetes_network_cidr }} --kubernetes-version="{{ kubernetes_version }}"
  args:
    creates: /etc/kubernetes/admin.conf
  register: init_output

- name: Save kubeadm join command to local file
  ansible.builtin.copy:
    content: "{{ init_output.stdout_lines[-2] }}"
    dest: "./join_command.sh"
  delegate_to: localhost
  when: init_output is changed
