---
- name: Install required packages
  ansible.builtin.yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - curl
      - wget
      - git
      - net-tools
      - nano
      - ca-certificates
      - gnupg2
    state: present

- name: Add Docker repository
  ansible.builtin.yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    enabled: 1
    gpgcheck: 1
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install Docker CE
  ansible.builtin.yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Disable swap (required for Kubernetes)
  ansible.builtin.shell: |
    set -o pipefail; swapon --show | grep -q swap && swapoff -a
  changed_when: false
  failed_when: "'command not found' in result.stderr"

- name: Remove swap from fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^\s*UUID=[^ ]+\s+swap\s+swap'
    line: '#\0'
    backrefs: true
    backup: true
