---
- name: Prepare all nodes
  pre_tasks:
    - include_vars: "{{ inventory_dir }}/group_vars/all.yml"
  hosts: all
  roles:
    - common

- name: Setup Kubernetes master
  hosts: masters
  roles:
    - master

- name: Setup Kubernetes workers
  hosts: workers
  roles:
    - worker
